---

- name: Gathering facts about environment
  hosts: all:!windows:!local
  gather_facts: false

  tasks:
    - name: Gather facts
      timeout: 30
      ansible.builtin.setup:

    - name: Group the hosts by distribution and major version
      ansible.builtin.group_by:
        key: os_{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}
