---

- name: Get Automation Controllers from Inventory
  hosts: controller
  gather_facts: false
  tasks:
    - name: Grouping hosts by distribution
      when: inventory_hostname == groups['controller'][0]
      ansible.builtin.group_by:
        key: primary_controller

- name: AAP Controller Configuration
  hosts: primary_controller
  gather_facts: false
  become: false

  vars_prompt:
    - name: manifest_path
      prompt: Path to manifest file
      default: "~/.ansible/manifest.zip"

  module_defaults:
    group/awx.awx.controller:
      controller_host: "https://127.0.0.1"
      controller_username: admin
      controller_password: "{{ admin_password | default('admin') }}"
      validate_certs: false

  tasks:
    - name: Upload manifest to Automation Controller
      block:
        - name: Upload manifest to temp path on controller
          ansible.builtin.copy:
            src: "{{ manifest_path }}"
            dest: "/tmp/manifest.zip"

        - name: Upload manifest through API
          awx.awx.license:
            manifest: "/tmp/manifest.zip"
            state: present
            force: true

        - name: Remove manifest
          ansible.builtin.file:
            path: /tmp/manifest.zip
            state: absent

    - name: Configure project to use demonpig/aap-example-project
      awx.awx.project:
        name: Example Project
        organization: Default
        state: present
        scm_url: https://github.com/demonpig/aap-example-project
        scm_type: git
        scm_clean: true
        update_project: true

    - name: Configure the inventories
      loop:
        - name: Demo Inventory
          state: absent
        - name: Default Inventory
          state: present
      awx.awx.inventory:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        organization: Default

    - name: Add hosts to Default Inventory
      loop:
        - name: localhost
          variables:
            ansible_host: 127.0.0.1
            ansible_connection: local
        - name: managed1.local
          variables:
            ansible_host: "{{ hostvars['managed1.local']['ansible_host'] | default('127.0.0.1') }}"
      awx.awx.host:
        name: "{{ item.name }}"
        state: present
        variables: "{{ item.variables }}"
        enabled: true
        inventory: "Default Inventory"

    - name: Add SSH credential to log into hosts
      awx.awx.credential:
        name: cloud-user
        credential_type: Machine
        organization: Default
        inputs:
          username: "cloud-user"
          password: "cloud-user"

    - name: Remove Demo Job Template
      awx.awx.job_template:
        name: "Demo Job Template"
        state: absent

    - name: Create common job templates used for debugging
      loop:
        - name: Long
          playbook: playbooks/long.yml
        - name: Ping
          playbook: playbooks/ping.yml
      awx.awx.job_template:
        name: "{{ item.name }}"
        job_type: run
        organization: Default
        inventory: Default Inventory
        project: Example Project
        playbook: "{{ item.playbook }}"
        state: present
        allow_simultaneous: true
        credentials:
          - cloud-user
