apiVersion: v1
kind: Secret
metadata:
  # make sure name ends in `-database-secret`
  name: ""
  namespace: ""
stringData:
  host: ""
  port: ""
  database: ""
  username: ""
  password: ""
type: Opaque