---

apiVersion: v1
kind: Secret
metadata:
  # make sure name ends in `-ldap-secret`
  name: ""
  namespace: ""
stringData:
  auth_ldap_server_uri: ""
  auth_ldap_bind_dn: ""
  auth_ldap_bind_password: ""
  auth_ldap_group_search: LDAPSearch("",ldap.SCOPE_SUBTREE,"(objectClass=group)")
  auth_ldap_user_search: LDAPSearch("", ldap.SCOPE_SUBTREE, "(uid=%(user)s)")
  auth_ldap_group_type: MemberDNGroupType(name_attr='cn')